language: php

php:
  - 7.0
  - 7.1
  - 7.2
env:
  - TYPO3_VERSION=^7.6
  - TYPO3_VERSION=^8.7
  - TYPO3_VERSION=^9.5
matrix:
  fast_finish: true

sudo: false

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  - composer install
  - git checkout composer.json

script:
  - .Build/bin/phpcs -n --standard=PSR2 --extensions=php --ignore=Tests/Unit/Seeder/SeedTest.php ./Classes/ ./Tests/
  - .Build/bin/phpunit
