<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "seeder"
 *
 * Auto generated by Extension Builder 2016-04-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Seeder',
	'description' => 'Database Seeder for TYPO3',
	'category' => 'plugin',
	'author' => 'Dennis Römmich',
	'author_email' => 'dennis@roemmich.eu',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);